native jb_is_user_simon(id)

native jb_get_user_time(id)

native jb_get_user_points(id)

native jb_set_user_points(id, points)

native jb_is_box_active()

native jb_get_user_vpoints(id)

native jb_set_user_vpoints(id, vpoints)

native jb_has_user_bpammo(id)

native jb_get_day()

native jb_is_hns_day()

native jb_is_sns_day()

native jb_is_knife_day()

native jb_is_awp_day()

native jb_is_rambo_day()

native jb_is_nemesis_day()

native jb_is_rnemesis_day()

native jb_is_lms_day()

native jb_is_kingkong_day()

native jb_is_special_day()

native jb_get_alive_tplayers()

native jb_get_alive_ctplayers()

native jb_open()

native jb_has_user_knife(id)

native jb_is_user_kingkong(id)

native jb_is_user_president(id)

native jb_is_president_day()

native jb_is_given_bpammo(id)

native jb_is_user_last(id)

native jb_is_user_chameleon(id)

native jb_stop_special_day()

native jb_has_user_chainsaw(id)

native jb_is_user_banned(id)

native jb_reload_simon_command()

native is_user_gagged(id)