enum eMENUS
{
	WC3_NONE = 0, WC3_GIVEXP, WC3_TAKEXP, WC3_SETLEVEL, WC3_GIVEITEM, WC3_REMOVEITEM, WC3_GIVEGOLD, WC3_TAKEGOLD, WC3_RESETGOLD
}

new eMENUS:g_iMenuType[MAX_PLAYERS + 1], g_iPlayer[MAX_PLAYERS + 1];